apiVersion: apps/v1 
kind: Deployment
metadata:
  name: exam-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: examone 
  template:
    metadata:
      labels:
        app: examone
    spec:
      containers:
        - name: nginx
          image: exam 
          imagePullPolicy: Never
          ports:
          - containerPort: 80

